### ISSUE TITLE
爬取知乎回答数返回多余字符

### ISSUE THREAD

**Issue by flowingrain** [KKys/ZhiHuSpider#12]
正在抓取用户链接：https://www.zhihu.com/people/piaoyegege
Exception in thread "main" java.lang.NumberFormatException: For input string: "回答<span class="Tabs-meta">86"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at ZhiHuSpider.bean.ZhiHuUserBean.<init>(ZhiHuUserBean.java:109)
	at ZhiHuSpider.mothed.Spider.getTopUserInfo(Spider.java:89)
	at ZhiHuSpider.test.ZhiHuMain.main(ZhiHuMain.java:40)
![image](https://cloud.githubusercontent.com/assets/19755864/25791775/2a2c4b10-33f5-11e7-8204-efc237317424.png)
![image](https://cloud.githubusercontent.com/assets/19755864/25791859/bc1d017c-33f5-11e7-9cc8-88ca128c5505.png)

**Comment by KKys** [comment]
应该是知乎排版改了，可以调一下
