### ISSUE TITLE
貌似不能抓取“更多”按钮之后的图片？

### ISSUE THREAD

**Issue by qulongjun** [KKys/ZhiHuSpider#3]
只能抓取第一页的图片，更多之后的图片貌似抓取不到？

**Comment by KKys** [comment]
这个貌似得用js了，还在考虑怎么实现、、

**Comment by fangchenhui3** [comment]
我用了之后出现了这个错误
正在抓取知乎链接：https://www.zhihu.com/question/28594126
发送GET请求出现异常！java.io.IOException: HTTPS hostname wrong:  should be <www.zhihu.com>
java.io.IOException: HTTPS hostname wrong:  should be <www.zhihu.com>
	at sun.net.www.protocol.https.HttpsClient.checkURLSpoofing(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at mothed.Util.SendGet(Util.java:26)
	at bean.ZhiHuPicBean.<init>(ZhiHuPicBean.java:47)
	at mothed.Spider.downloadPic(Spider.java:21)
	at test.ZhiHuMain.main(ZhiHuMain.java:29)

标题：null


即将开始下载图片到D:/知乎爬虫/null

开始下载................


图片下载完毕，请到D:/知乎爬虫/null里去看看吧！！！
